int1=(input())
int2=(input())
print(((int(int1)+int(int2))))
print(((int(int1)-int(int2))))
print(((int(int1)//int(int2))))
print(((int(int1)*int(int2))))
print(((int(int1)%int(int2))))

print(((float(int1)%float(int2))))
print(((float(int1)+float(int2))))
print(((float(int1)-float(int2))))
print(((float(int1)//float(int2))))
print(((float(int1)*float(int2))))
